# Generated by Django 3.1.2 on 2021-12-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0016_auto_20211215_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('large_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_content', models.JSONField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('cat_supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_stp.cat_supplier')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.transferencia')),
            ],
        ),
    ]
