# Generated by Django 3.1.2 on 2021-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_stp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_transactions',
            name='consumption_date',
            field=models.DateTimeField(default=None),
        ),
    ]
