# Generated by Django 3.1.2 on 2021-12-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_stp', '0002_supplier_transactions_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_transactions',
            name='consumption_date',
            field=models.DateTimeField(),
        ),
    ]
