# Generated by Django 3.1.2 on 2021-08-24 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='caracteristicas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('monto', models.FloatField()),
                ('t_monto', models.CharField(choices=[('%', 'Porcentaje'), ('$', 'cantidad')], default='$', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='freq_cobro',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('frecuencia', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='rel_user_prod',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='rel_serv_cara',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('comisiones', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.caracteristicas')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='rel_prod_serv',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='cobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.freq_cobro'),
        ),
    ]
