# Generated by Django 3.1.2 on 2021-08-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210811_1020'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rel_user_prod',
            name='cuenta_rel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cuenta'),
        ),
        migrations.AlterField(
            model_name='rel_user_prod',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
