# Generated by Django 3.1.2 on 2021-08-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20210825_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rel_user_prod',
            name='cuenta_rel',
        ),
    ]
