# Generated by Django 3.1.2 on 2021-08-25 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_remove_rel_user_prod_cuenta_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicas',
            name='f_persona',
            field=models.ForeignKey(default=94, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Caracteristica_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 15, 45, 27, 356363)),
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='usuario_autorizacion',
            field=models.ForeignKey(default=94, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_autoriza', to=settings.AUTH_USER_MODEL),
        ),
    ]
