# Generated by Django 3.1.2 on 2021-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210826_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicas',
            name='comision',
            field=models.BooleanField(default=True),
        ),
    ]
