# Generated by Django 3.1.2 on 2021-07-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('idgadget', models.CharField(max_length=24, unique=True)),
                ('alias', models.CharField(blank=True, max_length=70, null=True)),
                ('monto', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombreT', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
