# Generated by Django 3.1.2 on 2021-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='monto_req_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='monto_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
