# Generated by Django 3.1.2 on 2021-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_detalle_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='referencia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
