# Generated by Django 3.2.8 on 2021-11-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_solicitudes_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='edosolicitud',
            name='descripcion',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
