# Generated by Django 3.2.8 on 2022-02-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0007_alter_solicitudes_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='fechaChange',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='personChange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='persona_autorizacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='personaSolicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='persona_solicita', to=settings.AUTH_USER_MODEL),
        ),
    ]
