# Generated by Django 3.2.8 on 2022-01-20 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0049_persona_token_device_app_token'),
        ('transaction', '0017_auto_20220111_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_commission',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('percent', models.DecimalField(decimal_places=4, max_digits=11)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=11)),
                ('description', models.CharField(max_length=150)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('total_payment_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_commission_apply',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=23)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_commission_status',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=23)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_commission_type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('commission_rel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commissions.cat_commission')),
                ('person_debtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pago_primario', to=settings.AUTH_USER_MODEL)),
                ('person_payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pago_secundario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commission_detail',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('mount', models.DecimalField(decimal_places=4, max_digits=11)),
                ('payment_date', models.DateField(default=None, null=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commissions.commission')),
                ('transaction_rel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.transferencia')),
            ],
        ),
        migrations.AddField(
            model_name='cat_commission',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commissions.cat_commission_apply'),
        ),
        migrations.AddField(
            model_name='cat_commission',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.productos'),
        ),
        migrations.AddField(
            model_name='cat_commission',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commissions.cat_commission_status'),
        ),
        migrations.AddField(
            model_name='cat_commission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commissions.cat_commission_type'),
        ),
    ]
