# Generated by Django 3.2.8 on 2022-01-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_commission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cat_commission',
            name='total_payment_date',
        ),
    ]
