# Generated by Django 3.2.8 on 2022-01-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_auto_20220121_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_commission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='total_payment_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='commission_detail',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='commissions.cat_commission_status'),
        ),
    ]
