# Generated by Django 3.2.8 on 2022-01-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20220121_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_commission',
            name='producto',
        ),
    ]
