# Generated by Django 3.2.8 on 2022-01-25 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20220125_1333'),
        ('commissions', '0006_remove_cat_commission_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_commission',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.rel_prod_serv'),
            preserve_default=False,
        ),
    ]
