# Generated by Django 3.1.2 on 2021-05-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('cuenta', models.CharField(max_length=18)),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('alias', models.CharField(max_length=45, null=True)),
            ],
            options={
                'permissions': [('can_create_contact_v2', 'Puede crear contacto'), ('can_edit_contact_v2', 'Puede editar contacto'), ('can_get_contact_v2', 'Puede ver contacto')],
            },
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombreGrupo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='grupoContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.contactos')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='contacts.grupo')),
            ],
        ),
    ]
