# Generated by Django 3.1.2 on 2021-05-27 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactos',
            name='tipo_contacto',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.tipo_transferencia'),
        ),
    ]
