# Generated by Django 3.1.2 on 2021-06-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210527_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='rfc_beneficiario',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
