# Generated by Django 3.1.2 on 2021-09-13 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactos_rfc_beneficiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='fechamodificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
