# Generated by Django 3.1.2 on 2021-10-28 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_auto_20210913_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatOperaciones',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=7)),
                ('descripcion', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contactos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HistoricoContactos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('datos', models.TextField(max_length=150)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('contactoRel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.contactos')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.catoperaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
