# Generated by Django 3.2.8 on 2022-02-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmitter',
            name='short_name',
            field=models.CharField(max_length=45),
        ),
    ]
