# Generated by Django 3.1.2 on 2022-03-07 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_pay', '0002_alter_transmitter_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Frequents',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('transmmiter_Rel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services_pay.transmitter')),
                ('user_rel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
