# Generated by Django 3.1.2 on 2022-03-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_pay', '0003_category_frequents'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitter',
            name='catRel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='services_pay.category'),
        ),
    ]
