# Generated by Django 3.1.2 on 2021-12-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_person',
            name='selected_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='languages.cat_languages'),
        ),
    ]
