# Generated by Django 3.1.2 on 2021-11-12 12:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0048_auto_20211025_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialesAPI',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.cuenta')),
            ],
        ),
    ]
