# Generated by Django 3.1.2 on 2021-11-24 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_client', '0003_credencialesapi_personarel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialesapi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
