# Generated by Django 3.1.2 on 2022-01-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='cat_supplier',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name_short', models.CharField(max_length=5, unique=True)),
                ('name_large', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_proveedor', to='suppliers.cat_type')),
            ],
        ),
        migrations.CreateModel(
            name='cat_products_params',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('json_content', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_relacionado', to='suppliers.cat_supplier')),
            ],
        ),
    ]
