# Generated by Django 3.1.2 on 2021-05-27 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=True)),
                ('fecha_nacimiento', models.DateField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(default='999999999999', max_length=13)),
                ('curp', models.CharField(default='CURPNOVALIDO', max_length=13)),
                ('ip_address', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('token_device', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'permissions': [('can_create_user_v2', 'Puede crear usuario'), ('can_edit_user_v2', 'Puede editar usuario'), ('can_get_user_v2', 'Puede ver usuario'), ('can_do_all_user_v1', 'Puede hacer todo')],
            },
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cuenta', models.CharField(editable=False, max_length=16)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField(default=0, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('cuentaclave', models.CharField(editable=False, max_length=18)),
                ('persona_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_transactions_v2', 'Puede crear transacciones'), ('can_edit_transactions_v2', 'Puede editar transacciones'), ('can_get_transactions_v2', 'Puede ver transacciones')],
            },
        ),
        migrations.CreateModel(
            name='t_persona',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tPersona', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tcuenta',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nTCuenta', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='trelacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombrerel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tarjeta', models.CharField(max_length=16, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('monto', models.FloatField(default=0, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('TarjetaId', models.BigIntegerField(unique=True)),
                ('ClaveEmpleado', models.CharField(max_length=50, null=True)),
                ('NumeroCuenta', models.CharField(max_length=50, null=True)),
                ('cvc', models.CharField(blank=True, default='n/a', max_length=3)),
                ('fechaexp', models.DateField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('cuenta', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cuenta')),
                ('tipo_cuenta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.tcuenta')),
            ],
            options={
                'permissions': [('can_create_transactions_v2', 'Puede crear transacciones'), ('can_edit_transactions_v2', 'Puede editar transacciones'), ('can_get_transactions_v2', 'Puede ver transacciones')],
            },
        ),
        migrations.CreateModel(
            name='grupoPersona',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('nombre_grupo', models.CharField(default=None, max_length=60, null=True)),
                ('addworker', models.BooleanField(default=False)),
                ('delworker', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresa', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='persona', to=settings.AUTH_USER_MODEL)),
                ('relacion_grupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.trelacion')),
            ],
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('acta', models.FileField(upload_to='acta')),
                ('rfc', models.FileField(upload_to='rfc')),
                ('constancia', models.FileField(upload_to='constancia')),
                ('identificacion', models.FileField(upload_to='identificacion')),
                ('curp', models.FileField(default=None, null=True, upload_to='curp')),
                ('authorization', models.BooleanField(default=False)),
                ('dateauth', models.DateField(null=True)),
                ('comentario', models.CharField(default=None, max_length=254, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_doctos', to=settings.AUTH_USER_MODEL)),
                ('userauth', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autoriza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_documents_v2', 'Puede crear documentos'), ('can_edit_documents_v2', 'Puede editar documentos'), ('can_get_user_v2', 'Puede ver documentos'), ('can_delete_documents_v2', 'Puede eliminar documentos')],
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='t_persona', to='users.t_persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
