# Generated by Django 3.1.2 on 2021-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='authActa',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Correcto'), ('D', 'Devuelto')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='documentos',
            name='authConstancia',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Correcto'), ('D', 'Devuelto')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='documentos',
            name='authCurp',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Correcto'), ('D', 'Devuelto')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='documentos',
            name='authRFC',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Correcto'), ('D', 'Devuelto')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='documentos',
            name='authidentificacion',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Correcto'), ('D', 'Devuelto')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='persona',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
