# Generated by Django 3.1.2 on 2021-06-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210602_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='authorization',
        ),
    ]
