# Generated by Django 3.1.2 on 2021-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_documentos_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='dateauthActa',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='dateauthConst',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='dateauthCurp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='dateauthID',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='dateauthRFC',
            field=models.DateTimeField(null=True),
        ),
    ]
