# Generated by Django 3.1.2 on 2021-06-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210609_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='authActa',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='authConstancia',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='authCurp',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='authRFC',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='authidentificacion',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='constancia',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='dateauthActa',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='dateauthConst',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='dateauthCurp',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='dateauthID',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='dateauthRFC',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='rfc',
        ),
        migrations.AddField(
            model_name='documentos',
            name='authorization',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='documentos',
            name='dateauth',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='documento',
            field=models.FileField(default=None, null=True, upload_to='documento'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='load',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Correcto'), ('D', 'Devuelto')], default='P',
                                   max_length=1),
        ),
        migrations.AddField(
            model_name='persona',
            name='rfc',
            field=models.CharField(default='NoData', max_length=13),
        ),
    ]
