# Generated by Django 3.1.2 on 2021-06-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210614_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='corte',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.cuenta')),
            ],
        ),
    ]
