# Generated by Django 3.1.2 on 2021-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
