# Generated by Django 3.1.2 on 2021-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_persona_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
