# Generated by Django 3.1.2 on 2021-06-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210630_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='alcaldia_mpio',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='codigopostal',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='no_exterior',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='no_interior',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='pais',
        ),
    ]
