# Generated by Django 3.1.2 on 2021-06-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210630_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='domicilio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('codigopostal', models.CharField(blank=True, max_length=6, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('alcaldia_mpio', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=250, null=True)),
                ('no_exterior', models.CharField(blank=True, max_length=5, null=True)),
                ('no_interior', models.CharField(blank=True, max_length=4, null=True)),
                ('pais', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='banco_clabe',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='clabeinterbancaria_dos',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='clabeinterbancaria_uno',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
