# Generated by Django 3.1.2 on 2021-06-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210630_1648'),
    ]

    operations = [

    ]
