# Generated by Django 3.1.2 on 2021-06-30 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_persona_fdomicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fdomicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.domicilio'),
        ),
    ]
