# Generated by Django 3.1.2 on 2021-07-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='clave_traspaso',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
