# Generated by Django 3.1.2 on 2021-07-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_persona_clave_traspaso'),
        ('users', '0002_persona_state'),
    ]

    operations = [
    ]
