# Generated by Django 3.1.2 on 2021-07-09 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_merge_20210706_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comisiones',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('comision', models.BooleanField(default=True)),
                ('porc_comision', models.FloatField(default=0.001)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField()),
                ('f_persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Comision_cliente', to=settings.AUTH_USER_MODEL)),
                ('f_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.productos')),
                ('usuario_autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SU_autoriza', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
