# Generated by Django 3.1.2 on 2021-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210709_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='tdocumento',
            field=models.CharField(choices=[('A', 'Acta Nacimiento/constitutiva'), ('R', 'RFC'), ('C', 'Constancia'), ('I', 'Identificacion'), ('CU', 'Curp'), ('CD', 'Comprobante de domicilio'), ('N', 'S/E'), ('EC', 'Estado de Cuenta'), ('RP', 'Registro Publico'), ('DP', 'Documento de Prevención')], default='N', max_length=3),
        ),
    ]
