# Generated by Django 3.1.2 on 2021-07-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210714_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='dateupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='historial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='dateUpdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='historial',
            field=models.BooleanField(default=False),
        ),
    ]
