# Generated by Django 3.1.2 on 2021-07-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210721_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fdomicilio',
        ),
    ]
