# Generated by Django 3.1.2 on 2021-07-21 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_persona_fdomicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='domicilioPersona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
