# Generated by Django 3.1.2 on 2021-07-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_domicilio_domiciliopersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
