# Generated by Django 3.1.2 on 2021-07-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_domicilio_domiciliopersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDocumento',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='tdocumento',
        ),
    ]
