# Generated by Django 3.1.2 on 2021-07-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210726_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nip',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='nip',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
