# Generated by Django 3.1.2 on 2021-07-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210722_1641'),
        ('users', '0031_auto_20210726_0109'),
    ]

    operations = [
    ]
