# Generated by Django 3.1.2 on 2021-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_cuenta_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='last_login',
            field=models.DateTimeField(default=None),
        ),
    ]
