# Generated by Django 3.1.2 on 2021-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210803_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='last_login',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
