# Generated by Django 3.1.2 on 2021-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210803_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='last_login_user',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='phone',
            field=models.CharField(default='999999999999', max_length=14),
        ),
    ]
