# Generated by Django 3.1.2 on 2021-08-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_rel_user_prod_cuenta_rel'),
        ('users', '0037_auto_20210811_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='rel_cuenta_prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
