# Generated by Django 3.1.2 on 2021-09-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210826_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusPolipay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreStatus', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='grupopersona',
            name='fechacreacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grupopersona',
            name='fechamod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='paramsProveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pametro', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fproveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.proveedores_tarj')),
            ],
        ),
    ]
