# Generated by Django 3.1.2 on 2021-09-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_tarjeta_statusinterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='trelacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grupopersona',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trelacion',
            name='nombrerel',
            field=models.CharField(max_length=50),
        ),
    ]
