# Generated by Django 3.1.2 on 2021-09-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210914_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreCom', models.TextField(max_length=30)),
                ('descripcion', models.TextField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo_tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cat_tarjeta'),
        ),
    ]
