# Generated by Django 3.1.2 on 2021-09-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_cat_tarjeta_costounit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='clientePrincipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
