# Generated by Django 3.1.2 on 2022-01-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20211025_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='token_device_app_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
