# Generated by Django 3.2.8 on 2022-01-26 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_access_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_credentials',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
