# Generated by Django 3.2.8 on 2022-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20220126_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
