# Generated by Django 3.1.2 on 2022-02-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_concentradosauxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentradosauxiliar',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
