# Generated by Django 3.1.2 on 2022-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20220212_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentradosauxiliar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
