# Generated by Django 3.1.2 on 2022-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20220212_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='motivo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
