# Generated by Django 3.1.2 on 2022-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20220428_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='name_stp',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
