# Generated by Django 3.1.2 on 2021-05-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bancos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('clabe', models.CharField(editable=False, max_length=3)),
                ('institucion', models.CharField(max_length=25)),
                ('participante', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_transferencia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='transmasivaprod',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('date_liberation', models.DateTimeField()),
                ('observations', models.CharField(max_length=254)),
                ('file', models.FileField(upload_to='excel_produccion')),
            ],
        ),
        migrations.CreateModel(
            name='transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('banco_beneficiario', models.CharField(max_length=5)),
                ('cta_beneficiario', models.CharField(max_length=16)),
                ('clave_rastreo', models.CharField(editable=False, max_length=30)),
                ('nombre_beneficiario', models.CharField(max_length=40)),
                ('rfc_curp_beneficiario', models.CharField(max_length=13)),
                ('tipo_cuenta', models.CharField(max_length=30)),
                ('monto', models.FloatField()),
                ('concepto_pago', models.CharField(max_length=40)),
                ('referencia_numerica', models.CharField(max_length=7)),
                ('institucion_operante', models.CharField(max_length=5)),
                ('empresa', models.CharField(max_length=40)),
                ('banco_emisor', models.CharField(max_length=5)),
                ('nombre_emisor', models.CharField(max_length=45)),
                ('cuenta_emisor', models.CharField(max_length=16)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(blank=True)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.bancos')),
            ],
            options={
                'permissions': [('can_create_transfer_v2', 'Puede crear transferencias'), ('can_edit_transfer_v2', 'Puede editar transferencias'), ('can_get_transfer_v2', 'Puede ver transferencias'), ('can_do_all_transfer_v2', 'Puede hacer todo')],
            },
        ),
    ]
