# Generated by Django 3.1.2 on 2021-05-27 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='cuentatransferencia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cuenta'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='masivo_trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_masiv', to='transaction.transmasivaprod'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='status_trans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.status'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='tipo_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.tipo_transferencia'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='user_autorizada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
