# Generated by Django 3.1.2 on 2021-06-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210527_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
