# Generated by Django 3.1.2 on 2021-08-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transferencia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='programada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='transferenciaProg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaProgramada', models.DateTimeField()),
                ('fechaEjecucion', models.DateTimeField()),
                ('transferReferida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.transferencia')),
            ],
        ),
    ]
