# Generated by Django 3.1.2 on 2021-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210811_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='banco_emisor',
            field=models.CharField(default='N/D', max_length=5),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='empresa',
            field=models.CharField(default='N/D', max_length=40),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='nombre_emisor',
            field=models.CharField(default='N/D', max_length=45),
        ),
    ]
