# Generated by Django 3.1.2 on 2021-09-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20210826_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencia',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_create_transfer_v2', 'Puede crear transferencias'), ('can_edit_transfer_v2', 'Puede editar transferencias'), ('can_get_transfer_v2', 'Puede ver transferencias'), ('can_do_all_transfer_v2', 'Puede hacer todo')]},
        ),
        migrations.AlterModelOptions(
            name='transmasivaprod',
            options={'ordering': ['-date_created']},
        ),
    ]
