# Generated by Django 3.1.2 on 2021-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210913_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='saldo_remanente',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
