# Generated by Django 3.1.2 on 2021-10-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20211025_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='catMaStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
