# Generated by Django 3.1.2 on 2021-10-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_catmastatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmasivaprod',
            name='statusRel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.catmastatus'),
        ),
    ]
