# Generated by Django 3.1.2 on 2021-10-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0010_transmasivaprod_statusrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmasivaprod',
            name='usuarioRel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
