# Generated by Django 3.1.2 on 2021-11-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_transmasivaprod_usuariorel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransMasivaProg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaProgramada', models.DateTimeField()),
                ('fechaEjecucion', models.DateTimeField()),
                ('masivaReferida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.transmasivaprod')),
            ],
        ),
    ]
