# Generated by Django 3.1.2 on 2021-11-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20211123_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='banco_beneficiario',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='banco_emisor',
        ),
    ]
