# Generated by Django 3.1.2 on 2021-11-30 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0014_auto_20211124_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencia',
            options={'permissions': [('can_create_transfer_v2', 'Puede crear transferencias'), ('can_edit_transfer_v2', 'Puede editar transferencias'), ('can_get_transfer_v2', 'Puede ver transferencias'), ('can_do_all_transfer_v2', 'Puede hacer todo')]},
        ),
        migrations.AddField(
            model_name='transferencia',
            name='emisor_empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emisorEmpresarial', to=settings.AUTH_USER_MODEL),
        ),
    ]
