# Generated by Django 3.1.2 on 2022-01-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20211215_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='institucion_operante',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='fecha_operacionSTP',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='folio_OpEF',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='rfc_curp_emisor',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='t_ctaBeneficiario',
            field=models.IntegerField(choices=[(1, 'SIN ESPECIFICAR'), (3, 'TARJETA DEBITO'), (10, 'TELEFONO CELULAR'), (40, 'CLABE')], default=1),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='t_ctaEmisor',
            field=models.IntegerField(choices=[(1, 'SIN ESPECIFICAR'), (3, 'TARJETA DEBITO'), (10, 'TELEFONO CELULAR'), (40, 'CLABE')], default=1),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='cta_beneficiario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='cuenta_emisor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='rfc_curp_beneficiario',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
