# Generated by Django 3.1.2 on 2022-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_auto_20220111_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='saldo_remanente_beneficiario',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
