# Generated by Django 3.1.2 on 2022-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_transferencia_saldo_remanente_beneficiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='referencia_numerica',
            field=models.CharField(max_length=50),
        ),
    ]
