# Generated by Django 3.1.2 on 2021-05-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type_report', models.CharField(choices=[('Robo o Extravio', 'Robo o Extravio'), ('Daño Fisico', 'Daño Fisico')], default='Robo o Extravio', max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
