# Generated by Django 3.1.2 on 2021-09-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_cat_tarjeta_costounit'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoReporte',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteCuentas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fechaReporte', models.DateTimeField(auto_now_add=True)),
                ('nombre_docto', models.CharField(max_length=30)),
                ('ext_docto', models.CharField(max_length=4)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('detalle', models.TextField()),
                ('cuentaRel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.cuenta')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.cattiporeporte')),
            ],
        ),
    ]
