# Generated by Django 3.1.2 on 2022-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycash', '0002_auto_20220621_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycashreference',
            name='comission_pay',
            field=models.FloatField(null=True),
        ),
    ]
