# Generated by Django 3.1.2 on 2022-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycash', '0004_auto_20220621_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycashreference',
            name='date_modify',
            field=models.DateTimeField(default=None),
        ),
    ]
