# Generated by Django 3.1.2 on 2021-11-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contacts', '0005_auto_20211028_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoGrupos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fechaRegistro', models.DateTimeField(auto_now=True)),
                ('fkGroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.catoperaciones')),
            ],
        ),
    ]
