# Generated by Django 3.1.2 on 2021-12-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='creation_data',
            new_name='creation_date',
        ),
    ]
