# Generated by Django 3.1.2 on 2022-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20220411_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_advise',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('tittle', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
