# Generated by Django 3.1.2 on 2022-04-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_general_advise'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_advise',
            name='btn_login',
            field=models.BooleanField(default=True),
        ),
    ]
